apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    environment: dev
    app: frontend
  ports:
    - port: 80            # Service port
      targetPort: http-web-svc      # Pod port
      nodePort: 30080     # Node port (range: 30000–32767)
