apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-ebs-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # used in dynamic provisioning
  awsElasticBlockStore:
    volumeID: vol-0aab723e666b585ef
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""  # used in dynamic provisioning
  volumeName: static-ebs-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
    - name: app
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: nginxhtml
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nginxhtml
      persistentVolumeClaim:
        claimName: static-ebs-pvc
