apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-01a7e107b9c30d8bf.efs.us-east-1.amazonaws.com
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-static-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-static-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-static-vol
    persistentVolumeClaim:
      claimName: efs-static-pvc
