apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:   # replicaset labels
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: # these labels shpuld match with pod labels
      app: nginx
      tier: frontend
      environment: dev
  template: # this is pod defination
    metadata:
      labels: # these are pod labels
        app: nginx
        tier: frontend
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
